### ISSUE TITLE
Getting warning about `set-output` command

### ISSUE THREAD

**Issue by kentcdodds** [SebRollen/toml-action#2]
I think this is going to be deprecated in favor of environment files:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by antoninbeaufort** [comment]
Seems done in https://github.com/SebRollen/toml-action/pull/1

**Comment by kentcdodds** [comment]
Thanks. Looks like that change should be tagged.

**Comment by SebRollen** [comment]
Tagged and released in https://github.com/SebRollen/toml-action/releases/tag/v1.0.1

**Comment by kentcdodds** [comment]
Thank you for taking the time to do this! 😁
