### ISSUE TITLE
Node version deprecated by GitHub

### ISSUE THREAD

**Issue by antoninbeaufort** [SebRollen/toml-action#3]
Hi, 
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: SebRollen/toml-action

>  We plan to migrate all actions to run on Node16 by Summer 2023

**Comment by SebRollen** [comment]
Thanks! This is fixed in version 1.0.2 https://github.com/SebRollen/toml-action/releases/tag/v1.0.2
